"""initial migration

Revision ID: f43f935df183
Revises: 
Create Date: 2026-03-03 09:23:40.653588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43f935df183'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_products_image_filename'), ['image_filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_is_approved'), ['is_approved'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vendor', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_users_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_is_vendor'), ['is_vendor'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_vendor'))
        batch_op.drop_index(batch_op.f('ix_users_is_admin'))
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_vendor')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_is_approved'))
        batch_op.drop_index(batch_op.f('ix_products_image_filename'))
        batch_op.drop_column('is_approved')
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
